### ISSUE TITLE
sha1 is deprecated

### ISSUE THREAD

**Issue by jslee02** [ros/homebrew-deps#16]
I got the following warnings while `brew doctor` with `console_bridge`, `urdfdom`, and `urdfdom-headers` installed:
```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/ros/homebrew-deps/console_bridge.rb:6:in `<class:ConsoleBridge>'
Please report this to the ros/deps tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/ros/homebrew-deps/urdfdom.rb:6:in `<class:Urdfdom>'
Please report this to the ros/deps tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/ros/homebrew-deps/urdfdom_headers.rb:6:in `<class:UrdfdomHeaders>'
Please report this to the ros/deps tap!
```

It seems homebrew is complaining in using deprecated keyword `sha1` in the formulas.

**Comment by jaewonshin** [comment]
Got the same issue. Any plan for resolving this?

**Comment by spaghetti-** [comment]
Fixed #19

**Comment by jslee02** [comment]
Thanks for the fix @spaghetti- ! Closing this issue.

**Comment by jaewonshin** [comment]
Thanks!
